### PR TITLE
Filter possible NaN y-values in all matern models

### PR DESCRIPTION
**Pull request by frthjf**
GPR already has it, this handles NaN for the other ones as well.

### CODE REVIEW

**Review by iraikov — COMMENTED** [review]
I understand that the default behavior of nan_to_num is to replace NaN with zero. Could we perhaps replace with a very large number? Otherwise, the surrogate might produce objective values that confuse the optimization.

**Comment by frthjf** [comment]
Good point. For the joint model I've tested the following max operation:
```python
 m = np.max(np.nan_to_num(y), axis=0)
 for c in range(y.shape[1]):
      y[:, c] = np.nan_to_num(y[:, c], nan=max(1e3 * m[c], 1e5)) 
```
but I ultimately found that it confused the model as well. It might be different for the GPs though. 

Another option would be to filter NaN values, but that means we are throwing out some information for non-NaN objectives.

I guess I can implement these options and then people can choose via `surrogate_kwargs`.

**Comment by iraikov** [comment]
When testing with GPs also found that replacing NaNs with zeroes confuses the optimization, which is why I chose to filter them out. Let's default to filtering out NaN's by default, and have an option for nan_to_num.


> Good point. For the joint model I've tested the following max operation:
> 
> ```python
>  m = np.max(np.nan_to_num(y), axis=0)
>  for c in range(y.shape[1]):
>       y[:, c] = np.nan_to_num(y[:, c], nan=max(1e3 * m[c], 1e5)) 
> ```
> 
> but I ultimately found that it confused the model as well. It might be different for the GPs though.
> 
> I guess I can implement these options and then people can choose via `surrogate_kwargs`.

**Comment by frthjf** [comment]
I agree, filtering as default seems safest / best.

**Review by iraikov — APPROVED** [review]
This looks good now, thanks for adding a configurable filter.

**Pull request merged**
